name: i18n
version: 0.06
abstract: Perl Internationalization Pragma
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.0
  Locale::Maketext: 0
  Locale::Maketext::Lexicon: 0
  Locale::Maketext::Simple: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
